# This CI Pipeline is used to make sure the website can be built
name: Build CI

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
      - name: Bun Setup
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install
      - name: Generate Static Website
        run: BASE_URL=/${{ github.event.repository.name }} bun generate
